/* Allegro datafile object indexes, produced by grabber v4.0.2, djgpp */
/* Datafile: c:\djgpp\project\objects.dat */
/* Date: Sun Dec 15 22:59:14 2002 */
/* Do not hand edit! */

#define FLAG_1                           0        /* BMP  */
#define FLAG_2                           1        /* BMP  */
#define FLAG_3                           2        /* BMP  */
#define FLAG_4                           3        /* BMP  */
#define FLAG_5                           4        /* BMP  */
#define FLAG_6                           5        /* BMP  */
#define FRUITL_DURIAN                    6        /* BMP  */
#define FRUITL_PINEAPPLE                 7        /* BMP  */
#define FRUITM_PEACH                     8        /* BMP  */
#define FRUITM_PEAR                      9        /* BMP  */
#define FRUITM_RAPPLE                    10       /* BMP  */
#define FRUITS_BLUEBERRY                 11       /* BMP  */
#define FRUITS_CHERRY                    12       /* BMP  */
#define FRUITS_FIG                       13       /* BMP  */
#define FRUITS_STRAWBERRY                14       /* BMP  */
#define OBJ_BASE1                        15       /* BMP  */
#define OBJ_BASE2                        16       /* BMP  */
#define OBJ_BASE3                        17       /* BMP  */
#define OBJ_BASE4                        18       /* BMP  */
#define OBJ_BASE5                        19       /* BMP  */
#define OBJ_BASE6                        20       /* BMP  */
#define OBJ_BLUEBOMB                     21       /* BMP  */
#define OBJ_BOUNCY                       22       /* BMP  */
#define OBJ_DIRTBOMB                     23       /* BMP  */
#define OBJ_FAT_BULLET                   24       /* BMP  */
#define OBJ_FIREBOMB                     25       /* BMP  */
#define OBJ_FRAG_GRENADE                 26       /* BMP  */
#define OBJ_GR_L                         27       /* BMP  */
#define OBJ_GRAIL                        28       /* BMP  */
#define OBJ_GRAPPLE_1                    29       /* BMP  */
#define OBJ_GRAPPLE_2                    30       /* BMP  */
#define OBJ_GRAPPLE_3                    31       /* BMP  */
#define OBJ_GRAPPLE_4                    32       /* BMP  */
#define OBJ_GRENADE                      33       /* BMP  */
#define OBJ_NRCKT_F                      34       /* BMP  */
#define OBJ_NRCKT_U1                     35       /* BMP  */
#define OBJ_NRCKT_U2                     36       /* BMP  */
#define OBJ_NRCKT_U3                     37       /* BMP  */
#define OBJ_NRCKT_U4                     38       /* BMP  */
#define OBJ_NRCKT_U5                     39       /* BMP  */
#define OBJ_NRCKT_U6                     40       /* BMP  */
#define OBJ_PKUP_ARM                     41       /* BMP  */
#define OBJ_PKUP_CLK                     42       /* BMP  */
#define OBJ_PKUP_HLTH                    43       /* BMP  */
#define OBJ_PKUP_SHLD                    44       /* BMP  */
#define OBJ_PKUP_WPN                     45       /* BMP  */
#define OBJ_PRONG1                       46       /* BMP  */
#define OBJ_PRONG2                       47       /* BMP  */
#define OBJ_PRONG3                       48       /* BMP  */
#define OBJ_PRONG4                       49       /* BMP  */
#define OBJ_PRONG5                       50       /* BMP  */
#define OBJ_RCKT_F                       51       /* BMP  */
#define OBJ_RCKT_U1                      52       /* BMP  */
#define OBJ_RCKT_U2                      53       /* BMP  */
#define OBJ_RCKT_U3                      54       /* BMP  */
#define OBJ_RCKT_U4                      55       /* BMP  */
#define OBJ_RCKT_U5                      56       /* BMP  */
#define OBJ_RCKT_U6                      57       /* BMP  */
#define OBJ_REDBOMB                      58       /* BMP  */
#define OBJ_RPG_F                        59       /* BMP  */
#define OBJ_RPG_U1                       60       /* BMP  */
#define OBJ_RPG_U2                       61       /* BMP  */
#define OBJ_RPG_U3                       62       /* BMP  */
#define OBJ_RPG_U4                       63       /* BMP  */
#define OBJ_RPG_U5                       64       /* BMP  */
#define OBJ_RPG_U6                       65       /* BMP  */
#define OBJ_SRCKT_F                      66       /* BMP  */
#define OBJ_SRCKT_U1                     67       /* BMP  */
#define OBJ_SRCKT_U2                     68       /* BMP  */
#define OBJ_SRCKT_U3                     69       /* BMP  */
#define OBJ_SRCKT_U4                     70       /* BMP  */
#define OBJ_SRCKT_U5                     71       /* BMP  */
#define OBJ_SRCKT_U6                     72       /* BMP  */
#define OBJ_TH_BASE_1                    73       /* BMP  */
#define OBJ_TH_BASE_2                    74       /* BMP  */
#define OBJ_TH_BASE_3                    75       /* BMP  */
#define OBJ_TH_BASE_4                    76       /* BMP  */
#define OBJ_TH_BASE_5                    77       /* BMP  */
#define OBJ_TH_BASE_6                    78       /* BMP  */
#define OBJ_TH_BASE_B                    79       /* BMP  */
#define OBJ_TH_BASE_B2                   80       /* BMP  */
#define OBJ_TH_BASE_FACE                 81       /* BMP  */
#define OBJECT_PALETTE                   82       /* PAL  */

